apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: argocdroles.rbac-operator.argoproj-labs.io
spec:
  group: rbac-operator.argoproj-labs.io
  names:
    kind: ArgoCDRole
    listKind: ArgoCDRoleList
    plural: argocdroles
    singular: argocdrole
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ArgoCDRole is the Schema for the roles API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ArgoCDRoleSpec defines the desired state of Role
            properties:
              rules:
                items:
                  properties:
                    objects:
                      items:
                        type: string
                      type: array
                    resource:
                      enum:
                      - clusters
                      - projects
                      - applications
                      - applicationsets
                      - repositories
                      - certificates
                      - accounts
                      - gpgkeys
                      - logs
                      - exec
                      - extensions
                      type: string
                    verbs:
                      items:
                        type: string
                      type: array
                  required:
                  - objects
                  - resource
                  - verbs
                  type: object
                type: array
            required:
            - rules
            type: object
          status:
            description: ArgoCDRoleStatus defines the observed state of Role
            properties:
              argocdRoleBindingRef:
                type: string
              conditions:
                items:
                  description: A Condition that may apply to a resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        LastTransitionTime is the last time this condition transitioned from one
                        status to another.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        A Message containing details about this condition's last transition from
                        one status to another, if any.
                      type: string
                    observedGeneration:
                      description: |-
                        ObservedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: A Reason for this condition's last transition from
                        one status to another.
                      type: string
                    status:
                      description: Status of this condition; is it currently True,
                        False, or Unknown?
                      type: string
                    type:
                      description: |-
                        Type of this condition. At most one of each condition type may apply to
                        a resource at any point in time.
                      type: string
                  required:
                  - lastTransitionTime
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions:
  - v1alpha1

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: argocdrolebindings.rbac-operator.argoproj-labs.io
spec:
  group: rbac-operator.argoproj-labs.io
  names:
    kind: ArgoCDRoleBinding
    listKind: ArgoCDRoleBindingList
    plural: argocdrolebindings
    singular: argocdrolebinding
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ArgoCDRoleBinding is the Schema for the argocdrolebindings API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ArgoCDRoleBindingSpec defines the desired state of ArgoCDRoleBinding
            properties:
              argocdRoleRef:
                properties:
                  name:
                    description: Name of the ArgoCDRole. Should not start with "role:"
                    type: string
                required:
                - name
                type: object
              subjects:
                items:
                  properties:
                    kind:
                      enum:
                      - sso
                      - local
                      - role
                      type: string
                    name:
                      description: Name of the subject. If Kind is "role", it shouldn't
                        start with "role:"
                      type: string
                  required:
                  - kind
                  - name
                  type: object
                type: array
            required:
            - argocdRoleRef
            - subjects
            type: object
          status:
            description: ArgoCDRoleBindingStatus defines the observed state of ArgoCDRoleBinding
            properties:
              conditions:
                items:
                  description: A Condition that may apply to a resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        LastTransitionTime is the last time this condition transitioned from one
                        status to another.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        A Message containing details about this condition's last transition from
                        one status to another, if any.
                      type: string
                    observedGeneration:
                      description: |-
                        ObservedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: A Reason for this condition's last transition from
                        one status to another.
                      type: string
                    status:
                      description: Status of this condition; is it currently True,
                        False, or Unknown?
                      type: string
                    type:
                      description: |-
                        Type of this condition. At most one of each condition type may apply to
                        a resource at any point in time.
                      type: string
                  required:
                  - lastTransitionTime
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions:
  - v1alpha1

---
