schema Workspace:
    artifact_path?: str
    auth_type?: str
    azure_client_id?: str
    azure_environment?: str
    azure_login_app_id?: str
    azure_tenant_id?: str
    azure_use_msi?: bool
    azure_workspace_resource_id?: str
    client_id?: str
    file_path?: str
    google_service_account?: str
    host?: str
    profile?: str
    resource_path?: str
    root_path?: str
    state_path?: str

